<?php

/**
 * @file
 * Primary module hooks for denistest module.
 *
 */


/**
 * Implements hook_entity_operation().
 */
function denistest_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  if($entity->getEntityTypeId() === 'node') {
      $operations = array();
      $operations['clone'] = array(
      'title' => t('Clone'),
      'url' => Drupal\Core\Url::fromRoute('denistest.nodeclone',["nid" => $entity->id()]),
      'weight' => 50,
      );

      return $operations;
  }
}